#include"screen.h"

void com()
{   
    
    SetCurrentCursorPos(2, 2);
    delay_print("응 좋아..");
    Sleep(500);
    SetCurrentCursorPos(2, 4);
    delay_print("....");
    SetCurrentCursorPos(2, 6);
    delay_print("집도착후");
    sound();
    SetCurrentCursorPos(2, 9);
    delay_print("---------------------------------------------------------------------------------------");
    SetCurrentCursorPos(2, 10);
    delay_print("|\033[44m준혁님(^3^):잘 도착했어?                                                              \033[0m|");
    SetCurrentCursorPos(2, 11);
    delay_print("|\033[44m                                                                                      \033[0m|");
    SetCurrentCursorPos(2, 12);
    delay_print("|\033[44mㅇㅇㅇ(^-^):웅 잘 도착했어                                                            \033[0m|");
    SetCurrentCursorPos(2, 13);
    delay_print("|\033[44m                                                                                      \033[0m|");
    SetCurrentCursorPos(2, 14);
    delay_print("|\033[44mㅇㅇㅇ(^-^):근데 나 궁금한거 있어                                                     \033[0m|");
    SetCurrentCursorPos(2, 15);
    delay_print("|\033[44m                                                                                      \033[0m|");
    SetCurrentCursorPos(2, 16);
    delay_print("|\033[44mㅇㅇㅇ(^-^):너랑 나 만난지 얼마 안됐는데 고백 왜 받아줬어?..?                         \033[0m|");
    SetCurrentCursorPos(2, 17);
    delay_print("|\033[44m                                                                                      \033[0m|");
    SetCurrentCursorPos(2, 18);
    delay_print("|\033[44m준혁님(^3^):아.. 그 너 내앞에서 넘어졌을때 봤는데 너 당황했던 모습 귀여워서           \033[0m|");
    SetCurrentCursorPos(2, 19);
    delay_print("|\033[44m                                                                                      \033[0m|");
    SetCurrentCursorPos(2, 20);
    delay_print("|\033[44m준혁님(^3^):계속 지켜본거 같아                                                        \033[0m|");
    SetCurrentCursorPos(2, 21);
    delay_print("|\033[44m                                                                                      \033[0m|");
    SetCurrentCursorPos(2, 22);
    delay_print("|\033[44mㅇㅇㅇ(^-^):아 진짜??(앤 그 .. 내가 수업중에 방구껴서 깬 사건.. 모르나 ..? 다행이다..)\033[0m|");
    SetCurrentCursorPos(2, 23);
    delay_print("|\033[44m                                                                                      \033[0m|");
    SetCurrentCursorPos(2, 24);
    delay_print("|\033[44m준혁님(^3^):우리 잘해보자                                                             \033[0m|");
    SetCurrentCursorPos(2, 25);
    delay_print("---------------------------------------------------------------------------------------");
    SetCurrentCursorPos(2, 27);
    printf("><..사실 .. 이건 제 친구 이야기에용^^");
}


void text1()
{
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), 15); //15: 하얀색
    SetCurrentCursorPos(2, 20);
    printf("----------------------------------------------------------------------------");
    Sleep(500);
    SetCurrentCursorPos(3, 3);
    printf("나는 000");
    Sleep(500);
    SetCurrentCursorPos(3, 5);
    printf("ㅇㅇㅇ은 연애를 하고싶다... ");
    Sleep(500);
    SetCurrentCursorPos(3, 7);
    printf("도서관에서 공부하는 ㅇㅇㅇ은 한남자를 보았다. ");
    Sleep(500);
    SetCurrentCursorPos(3, 9);
    printf("ㅇㅇㅇ의 눈에는 그가 멋있어보였다....그래도 ㅇㅇㅇ은 생각했다.");
    Sleep(500);
    SetCurrentCursorPos(3,11);
    printf(" '뭐.. 근데 잘생기긴 했지만 내스타일은 아니네...' ");
    Sleep(500);
    SetCurrentCursorPos(3, 13);
    printf("그때까지는 아무생각이 없었다...그 일이 있기전에는... ");
    Sleep(1000);
    sound();
    SetCurrentCursorPos(3, 15);
    delay_print("----------------------");
    SetCurrentCursorPos(3, 16);
    delay_print("|\033[44m야! 너 소개 안받을래?\033[0m|");
    SetCurrentCursorPos(3, 17);
    delay_print("----------------------");
    Sleep(1000);
    SetCurrentCursorPos(26, 16);
    printf("생각을 하고 있던 와증에 친구한테 문자가 왔다..");
    Sleep(500);
    SetCurrentCursorPos(26, 17);
    printf("어떻게 해야지?");
    Sleep(500);
    SetCurrentCursorPos(3, 22);
    printf("1.받지않는다.   2.받는다.  3.누구지?");
    SetCurrentCursorPos(0, 26);
    printf("\033[33m번호를 입력해주세요:\033[0m");

}

void text2()
{
    RemoveCursor();
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), 15); //15: 하얀색
    Sleep(1000);
    SetCurrentCursorPos(3, 2);
    printf("잠시뒤...");
    sound();
    Sleep(1000);
    SetCurrentCursorPos(3, 4);
    printf("카톡하고 울리는 소리에... 핸드폰을 보니");
    Sleep(1000);
    SetCurrentCursorPos(3, 5);
    printf("친구한테 연락이왔다..뭐라왔지?");
    SetCurrentCursorPos(3, 7);
    delay_print("----------------------");
    SetCurrentCursorPos(3, 8);
    delay_print("|\033[44m야 애 진짜 괜찮은애야\033[0m|");
    SetCurrentCursorPos(3, 9);
    delay_print("----------------------");
    Sleep(1000);
    SetCurrentCursorPos(3, 11);
    printf("라고 친구의 답장을 봤는데도...");
    Sleep(500);
    SetCurrentCursorPos(3, 12);
    printf("상대가 궁금은 하지만 혼자가 편하다는 생각을 못버리겠다..");
    Sleep(500);
    SetCurrentCursorPos(3, 13);
    printf("아.. 근데 난 역시 혼자가 편해..!!!!!!!!");
    SetCurrentCursorPos(3, 15);
    delay_print("---------------------");
    SetCurrentCursorPos(3, 16);
    delay_print("|\033[44m웅 나 혼자 살란다...\033[0m|");
    SetCurrentCursorPos(3, 17);
    delay_print("---------------------");
    Sleep(500);
    SetCurrentCursorPos(3, 19);
    printf("라고 보낸고 난뒤..");
    Sleep(500);
    sound();
    SetCurrentCursorPos(3, 21);
    printf("띠링 하고 카톡음이 울리고 ..");
    SetCurrentCursorPos(3, 24);
    delay_print("...");
    Sleep(1000);
    system("cls");
    Sleep(1000);
    SetCurrentCursorPos(2, 2);
    delay_print("------------------------------------------------------");
    SetCurrentCursorPos(2, 3);
    delay_print("|\033[44m친구다(^>^):진짜 괜찮은 애인데 어쩔 수 없지ㅋㅋ ㅜㅜ \033[0m|");
    SetCurrentCursorPos(2, 4);
    delay_print("|\033[44mㅇㅇㅇ(^-^):웅 나는 혼자가 좋아                      \033[0m|");
    SetCurrentCursorPos(2, 5);
    delay_print("|\033[44m친구임(^>^):ㅋㅋㅋㅋㅋㅋㅋ역시 ㅇㅇㅇ 지금 학교야?   \033[0m|");
    SetCurrentCursorPos(2, 6);
    delay_print("|\033[44m친구임(^>^):오 ~~ 나는 수업없는데                    \033[0m|");
    SetCurrentCursorPos(2, 7);
    delay_print("|\033[44mㅇㅇㅇ(^-^):ㅋㅋㅋ부러워ㅜㅜ 아 나 수업들으러가야해..\033[0m|");
    SetCurrentCursorPos(2, 8);
    delay_print("|\033[44m친구임(^>^):무슨 수업인데?                           \033[0m|");
    SetCurrentCursorPos(2, 9);
    delay_print("|\033[44mㅇㅇㅇ(^-^):경제학                                   \033[0m|");
    SetCurrentCursorPos(2, 10);
    delay_print("|\033[44m                                                     \033[0m|");
    SetCurrentCursorPos(2, 11);
    delay_print("|\033[44m ... 몇분 뒤..                                       \033[0m|");
    Sleep(1000);
    SetCurrentCursorPos(2, 12);
    delay_print("|\033[44m                                                     \033[0m|");
    SetCurrentCursorPos(2, 13);
    delay_print("|\033[44mㅇㅇㅇ(^-^):아.. 망했다                              \033[0m|");
    SetCurrentCursorPos(2, 14);
    delay_print("|\033[44m친구임(^>^):왜?무슨일인데                            \033[0m|");
    SetCurrentCursorPos(2, 15);
    delay_print("|\033[44mㅇㅇㅇ(^-^):그 내가 잘생겼다고 했던 애 기억나?...    \033[0m|");
    SetCurrentCursorPos(2, 16);
    delay_print("|\033[44mㅇㅇㅇ(^-^):나 개랑 같은 조 됐어..                   \033[0m|");
    SetCurrentCursorPos(2, 17);
    delay_print("|\033[44m친구임(^>^):?엥?개? 도서관앞에서 넘어진?             \033[0m|");
    SetCurrentCursorPos(2, 18);
    delay_print("|\033[44mㅇㅇㅇ(^-^):웅..그리고 사건이 하나 더 있어ㅜㅜ       \033[0m|");
    SetCurrentCursorPos(2, 19);
    delay_print("|\033[44m친구임(^>^):ㅋㅋ이정도면 인연이다 생각하고 친해져ㄱ  \033[0m|");
    SetCurrentCursorPos(2, 20);
    delay_print("|\033[44mㅇㅇㅇ(^-^):니 일 아니라고 함부로 말 ㄴㄴ            \033[0m|");
    SetCurrentCursorPos(2, 21);
    delay_print("------------------------------------------------------");
    Sleep(100);
    SetCurrentCursorPos(2, 23);
    printf("10분후");
    Sleep(1000);
    system("cls");
    Sleep(1000);
    SetCurrentCursorPos(2, 2);
    printf("친구와의 카톡이 끝난뒤에 과제를 하러 가야겠다 라고 마음을 먹었는데!!");
    Sleep(500);
    SetCurrentCursorPos(2, 4);
    printf("이럴수가... 과제를 까먹었어...;;");
    Sleep(500);
    SetCurrentCursorPos(2, 6);
    printf("어떻게해야하지? .. 아 .. 나랑 같이 경제학 듣는..사람이...?..개 한테 라도 보내야하나.. 정말 싫은데..");
    Sleep(500);
    SetCurrentCursorPos(2, 8);
    printf("개 한테 라도 보내야하나.. 정말 싫은데..그래도 해야겠지?..");
    Sleep(500);
    SetCurrentCursorPos(2, 10);
    delay_print("--------------------------------------");
    SetCurrentCursorPos(2, 11);
    delay_print("|\033[44m                                     \033[0m|");
    SetCurrentCursorPos(2, 12);
    delay_print("|\033[44m1.  저기..                           \033[0m|");
    SetCurrentCursorPos(2, 13);
    delay_print("|\033[44m                                     \033[0m|");
    SetCurrentCursorPos(2, 14);
    delay_print("|\033[44m2.자니 ? ..뭐하나만 물어봐도 될까 ?..\033[0m|");
    SetCurrentCursorPos(2, 15);
    delay_print("|\033[44m                                     \033[0m|");
    SetCurrentCursorPos(2, 16);
    delay_print("|\033[44m3. 그 .. 준혁님..                    \033[0m|"); 
    SetCurrentCursorPos(2, 17);
    delay_print("|\033[44m                                     \033[0m|");
    SetCurrentCursorPos(2, 18);
    delay_print("--------------------------------------");
    SetCurrentCursorPos(2, 20);
    printf("\033[34m1. 저기..\033[0m");
    SetCurrentCursorPos(2, 22);
    printf("\033[34m2. 자니 ? ..뭐하나만 물어봐도 될까 ? ..\033[0m");
    SetCurrentCursorPos(2, 24);
    printf("\033[34m3. 그 .. 준혁님..\033[0m");
    SetCurrentCursorPos(0, 26);
    printf("\033[33m번호를 입력해주세요:\033[0m");
    
    

}   

void text3() {

    sound2();
    Sleep(1000);
    SetCurrentCursorPos(3, 4);
    printf("두근두근... 근데 아 이게 뭐라고 떨리냐..");
    Sleep(1000);
    SetCurrentCursorPos(3, 6);
    printf("아 괜히 물어봤나?,, 괜히 실수 하는 거 같네");
    Sleep(500);
    SetCurrentCursorPos(3, 8);
    printf("안친한데..물어봐서 어색해지는거 아닌가.. 아 싫은데,,");
    Sleep(1000);
    SetCurrentCursorPos(3, 10);
    printf("아 근데 애는 씹나?!! 슬슬 화나네..");
    Sleep(500);
    SetCurrentCursorPos(3, 12);
    printf(",,애 안보면 나 큰일나는데,,과제 물어 볼 사람도 없고ㅜㅜ");
    Sleep(500);
    SetCurrentCursorPos(3, 14);
    printf("아,,친구라도 사귈껄.. 애도 조별 과제 때문에 알게 된건데..");
    Sleep(500);
    SetCurrentCursorPos(3, 16);
    delay_print("....");
    sound();
    SetCurrentCursorPos(3, 18);
    printf("띠링 하고 카톡음이 울리고..");
    Sleep(500);
    SetCurrentCursorPos(3, 20);
    delay_print("....");
    Sleep(500);
    SetCurrentCursorPos(3, 23);
    printf("드디어 답장해줬네");
    Sleep(1000);
    system("cls");
    Sleep(1000);
    SetCurrentCursorPos(2, 2);
    delay_print("-----------------------------------------------------");
    SetCurrentCursorPos(2, 3);
    delay_print("|\033[44mㅇㅇ님 늦게 봐서 죄송해요 제가 지금 밖에 놔와서 ㅠㅠ\033[0m|");
    SetCurrentCursorPos(2, 4);
    delay_print("|\033[44m                                                    \033[0m|");
    SetCurrentCursorPos(2, 5);
    delay_print("|\033[44m졍마로 죄송해요ㅜㅜ ..(일부로 오타낸거임)           \033[0m|");
    SetCurrentCursorPos(2, 6);
    delay_print("|\033[44m                                                    \033[0m|");
    Sleep(500);
    SetCurrentCursorPos(2, 7);
    delay_print("|\033[44m아..제가 오타가나서 죄송합니다ㅜㅜ                  \033[0m|");
    SetCurrentCursorPos(2, 8);
    delay_print("|\033[44m                                                    \033[0m|");
    Sleep(500);
    SetCurrentCursorPos(2, 12);
    printf("뭐지?...술마셨나?.. 말투가 왜이래");
    Sleep(1000);
    SetCurrentCursorPos(2, 9);
    delay_print("|\033[44m미미경제학 10장부터 13장까지에요ㅠㅠ                \033[0m|");
    SetCurrentCursorPos(2, 10);
    delay_print("-----------------------------------------------------");
    SetCurrentCursorPos(2, 14);
    printf("아.. 답장을 해야하는데 뭐라해야지?..");
    Sleep(500);
    SetCurrentCursorPos(2, 15);
    delay_print("---------------------------");
    SetCurrentCursorPos(2, 16);
    delay_print("|\033[44mㅇㅇㅇ(^-^): ...          \033[0m|");
    SetCurrentCursorPos(2, 17);
    delay_print("---------------------------");
    SetCurrentCursorPos(2, 18);
    delay_print("진짜 할 말이 없는데 걍 씹을까?..아니야 양심이 있는데..");
    Sleep(500);
    SetCurrentCursorPos(2, 20);
    printf("\033[34m1.넵 감사합니다.\033[0m");
    SetCurrentCursorPos(2, 22);
    printf("\033[34m2.정말 고마워요!혹시 술 드셨어요?\033[0m");
    SetCurrentCursorPos(2, 24);
    printf("\033[34m3.생명의 은인이에요 다음에 밥사드릴께요!\033[0m");
    SetCurrentCursorPos(0, 26);
    printf("\033[33m번호를 입력해주세요:\033[0m");

}

void text4()
{
    SetCurrentCursorPos(2, 1);
    delay_print("일단 답장은 보냈는데");
    Sleep(500);
    SetCurrentCursorPos(2, 2);
    delay_print("애는 술마시고 카톡 보낸거야? 좀 그렇네..");
    SetCurrentCursorPos(2, 3);
    printf("그래도 내가 물어본 입장이니깐 답장해준것만으로도 고마워 해야하나?..");
    Sleep(500);
    SetCurrentCursorPos(2, 4);
    printf("근데 애는 낮부터 술마시나?.. 신기하네..");
    Sleep(500);
    SetCurrentCursorPos(2, 5);
    printf("아..부럽다 애는 낮부터 술마실 학교 친구라도 있는거네 난 없는데..");
    Sleep(500);
    SetCurrentCursorPos(2, 6);
    printf("난 없는데.. 그래도 과제 알려줘서 내일 수업과제 하고 갈 수 있어서 다행이네");
    Sleep(500);
    SetCurrentCursorPos(2, 8);
    printf("(학교)");
    Sleep(500);
    SetCurrentCursorPos(2, 10);
    printf("'저기에 개 보이네.. 그래도 고맙다는 말 한번 더 해야겠지?");
    Sleep(500);
    SetCurrentCursorPos(2, 11);
    printf("어제 과제 알려줘서 감사해요");
    Sleep(500);
    SetCurrentCursorPos(2, 13);
    printf("아니에요 제가 어제 늦게 알려줘서 죄송합니다..");
    Sleep(500);
    SetCurrentCursorPos(2, 15);
    printf("'...정적은.. 뭐지? 어색해죽을꺼같아.. 빨리 말 끊고 가야겠다'");
    Sleep(500);
    SetCurrentCursorPos(2, 17);
    printf("아니에요 그래도 준혁님 덕분에 해결했어요.. 저는 이만..");
    Sleep(500);
    SetCurrentCursorPos(2, 19);
    printf("네 그럼");
    Sleep(500);
    SetCurrentCursorPos(2, 21);
    delay_print("이번에는 조별과제네..");
    SetCurrentCursorPos(2, 23);
    delay_print(".....");
    Sleep(1000);
    system("cls");
    Sleep(1000);
    SetCurrentCursorPos(2, 5);
    printf("(조별과제 끝난 후)");
    Sleep(1000);
    system("cls");
    Sleep(1000);
    SetCurrentCursorPos(2, 1);
    printf("또 둘이 남았네.. 다른사람들은 왜 이렇게 빨리나가는거야?.. ");
    Sleep(500);
    SetCurrentCursorPos(2, 3);
    printf("어색해.. 말이라도 걸어야하나?..");
    Sleep(500);
    SetCurrentCursorPos(2, 5);
    printf("저기 ㅇㅇ님..");
    Sleep(500);
    SetCurrentCursorPos(2, 7);
    printf("네? (왜 말걸지..)");
    Sleep(500);
    SetCurrentCursorPos(2, 9);
    printf("지하철 타러 가는 길 이에요?");
    Sleep(500);
    SetCurrentCursorPos(2, 11);
    printf("아니요 저 편의점 가는 길이에요");
    Sleep(500);
    SetCurrentCursorPos(2, 13);
    printf("아.. 저도 지금 혹시 편의점 갈껀데..");
    SetCurrentCursorPos(2, 15);
    printf("그럼 같이 가요..");
    Sleep(500);
    SetCurrentCursorPos(2, 17);
    printf("(편의점 갔다 온 후)");
    Sleep(1000);
    system("cls");
    Sleep(1000);
    SetCurrentCursorPos(2, 1);
    delay_print("--------------------------------------------------------------------");
    SetCurrentCursorPos(2, 2);
    delay_print("|\033[44mㅇㅇㅇ(^-^):야.. 나 큰일났어..                                    \033[0m|");
    SetCurrentCursorPos(2, 3);
    delay_print("|\033[44m친구임(^>^):또 왜그래???                                          \033[0m|");
    SetCurrentCursorPos(2, 4);
    delay_print("|\033[44mㅇㅇㅇ(^-^):나 금사빠인가봐.. 오랜만에 남자랑 대화했더니 설레네.. \033[0m|");
    SetCurrentCursorPos(2, 5);
    delay_print("|\033[44m친구임(^>^):ㄴㄴ 개 잘생겼다며 그래서 그런거야                    \033[0m|");
    SetCurrentCursorPos(2, 6);
    delay_print("|\033[44mㅇㅇㅇ(^-^):그건 인정.. 아님 내가 친구가 없어서?!!!               \033[0m|");
    SetCurrentCursorPos(2, 7);
    delay_print("|\033[44m친구임(^>^):ㅋㅋㅋ그럴수도 이 기회에 친구로 지내자고 ㄱ           \033[0m|");
    SetCurrentCursorPos(2, 8);
    delay_print("|\033[44mㅇㅇㅇ(^-^):그럴까?.. 근데 나 애랑 안친한데 말한적도 2번뿐???     \033[0m|");
    SetCurrentCursorPos(2, 9);
    delay_print("|\033[44m친구임(^>^):그럼 너가 다가가서 친해지자고 해                      \033[0m|");
    SetCurrentCursorPos(2, 10);
    delay_print("|\033[44mㅇㅇㅇ(^-^):아 싫은데.. 근데 내가 해야지겠지?..                   \033[0m|");
    SetCurrentCursorPos(2, 11);
    delay_print("|\033[44m친구임(^>^):웅 그때 편의점도 갔다며 그리고 너 개한테 얻은거 있자나\033[0m|");
    SetCurrentCursorPos(2, 12);
    delay_print("|\033[44mㅇㅇㅇ(^-^):마져 보답해야지                                       \033[0m|");
    SetCurrentCursorPos(2, 13);
    delay_print("--------------------------------------------------------------------");
    Sleep(500);
    SetCurrentCursorPos(2, 15);
    printf("일단.....");
    SetCurrentCursorPos(2, 17);
    delay_print("------------------------------------------------");
    SetCurrentCursorPos(2, 18);
    delay_print("|\033[44m저기.. 그때 과제 감사해서 보답 해야할꺼같아서요\033[0m|");
    SetCurrentCursorPos(2, 19);
    delay_print("|\033[44m ...                                           \033[0m|");
    SetCurrentCursorPos(2, 20);
    delay_print("------------------------------------------------");
    Sleep(500);
    SetCurrentCursorPos(2, 22);
    printf("\033[34m1.제가 한강에서 맛있는거 사드릴께요!! 저랑 한강갈래요?..\033[0m");
    SetCurrentCursorPos(2, 23);
    printf("\033[34m2.지금 뭐하세요?.. 할 일 없으면 나오실래요?...\033[0m");
    SetCurrentCursorPos(2, 24);
    printf("\033[34m3.친해질겸 술 한잔 하실래요?..\033[0m"); 
    SetCurrentCursorPos(0, 26);
    printf("\033[33m번호를 입력해주세요:\033[0m");

}

void text5()
{
    SetCurrentCursorPos(2, 1);
    printf("근데 .. 나 잘한거 맞겠지?.. 아씨.. 내가 미쳤나?..");
    Sleep(500);
    SetCurrentCursorPos(2, 2);
    printf("....이게 뭐라고.. 아 나 친구로 만들고 싶은거 맞겠지?.. 남친이아니라..");
    SetCurrentCursorPos(2, 4);
    delay_print("...");
    sound();
    SetCurrentCursorPos(2, 5);
    printf("띠링 카톡이 울리고..");
    Sleep(500);
    SetCurrentCursorPos(2, 7);
    delay_print("...");
    SetCurrentCursorPos(2, 8);
    printf("뭐라왔지?...");
    Sleep(500);
    SetCurrentCursorPos(2, 10);
    delay_print("------------------------------------");
    SetCurrentCursorPos(2, 11);
    delay_print("|\033[44m준혁님(^3^):네 좋아요!             \033[0m|");
    Sleep(500);
    SetCurrentCursorPos(2, 17);
    delay_print("... 괜히 보냈나?.. 바로 수락하니깐 살짝 부담스럽네");
    SetCurrentCursorPos(2, 18);
    delay_print("근데 언제봐야 좋은거지?");
    Sleep(500);
    SetCurrentCursorPos(2, 12);
    delay_print("|\033[44mㅇㅇㅇ(^-^):언제 시간 좋아요?      \033[0m|");
    SetCurrentCursorPos(2, 13);
    delay_print("|\033[44m준혁님(^3^):저 다 상관없어요!!     \033[0m|");
    SetCurrentCursorPos(2, 14);
    delay_print("|\033[44mㅇㅇㅇ(^-^):그럼 ㅇㅇ일 ㅇ시에 봐요\033[0m|");
    SetCurrentCursorPos(2, 15);
    delay_print("|\033[44m준혁님(^3^):좋아요 그날에 봐요     \033[0m|");
    SetCurrentCursorPos(2, 16);
    delay_print("------------------------------------");
    SetCurrentCursorPos(2, 20);
    printf("이거 잘 한짓 맞겠지?");
    Sleep(500);
    SetCurrentCursorPos(2, 22);
    printf("(시간이 흐르고 ..한강가는날)");
    Sleep(1000);
    SetCurrentCursorPos(2, 23);
    printf("이게 뭐라고 긴장되냐..");
    Sleep(500);
    SetCurrentCursorPos(2, 24);
    printf("정신차려 이건 친구 만들러 가는거야");
    Sleep(1000);
    system("cls");
    Sleep(1000);
    SetCurrentCursorPos(2, 1);
    printf("저기 서있는 분인가?... 맞는거 같은데..가까이 가보자!");
    Sleep(500);
    SetCurrentCursorPos(2, 2);
    printf("맞네.. 안녕하세요?");
    Sleep(500);
    SetCurrentCursorPos(2, 3);
    printf("네!! ..근데.. 저희 동갑인데 말 놓을까요?..");
    Sleep(500);
    SetCurrentCursorPos(2, 4);
    printf("응 좋아(드디어 말 놨네..)");
    Sleep(500);
    SetCurrentCursorPos(2, 6);
    delay_print("한강도착 ..(시간이 흐르고..)");
    SetCurrentCursorPos(2, 8);
    delay_print("(노래도 나오고 해도짐)");
    Sleep(1000);
    system("cls");
    Sleep(1000);
    SetCurrentCursorPos(2, 1);
    delay_print("와 .. 여기 너무 이쁜거같아..");
    SetCurrentCursorPos(2, 4);
    delay_print("마자 그리고 라면도 완전 맛있어");
    SetCurrentCursorPos(2, 6);
    delay_print("'뭐지 이 분위기? 그리고 애 알수록 성격도 괜찮네'");
    SetCurrentCursorPos(2, 7);
    delay_print("'그리고 밤이라서 그런지 더 잘생겨보여..'");
    SetCurrentCursorPos(2, 9);
    delay_print("ㅇㅇ아 왜 멍때려 무슨생각하고있어?");
    SetCurrentCursorPos(2, 11);
    delay_print("너생각.. 어? 나 무슨 말했지? 미쳤나봐..");
    SetCurrentCursorPos(2, 13);
    delay_print("ㅋㅋㅋㅋㅋㅋㅋ귀엽네");
    SetCurrentCursorPos(2, 15);
    printf("'..뭐지 애 왜 설레게하냐..' 한강생각했어!!");
    Sleep(500);
    SetCurrentCursorPos(2, 16);
    printf("근데 너 왜 여자친구 안사겨?(나 취했나?..왜 이런걸..)");
    Sleep(500);
    SetCurrentCursorPos(2, 18);
    printf("사귀고는 싶은데 주위에 사람이없어");
    Sleep(500);
    SetCurrentCursorPos(2, 19);
    printf("엥? 너 인싸같던데");
    Sleep(500);
    SetCurrentCursorPos(2, 20);
    printf("아니야 나 원래 밖에 잘 안나가");
    Sleep(1000);
    system("cls");
    Sleep(1000);
    SetCurrentCursorPos(2, 1);
    delay_print("....");
    SetCurrentCursorPos(2, 3);
    delay_print("....");
    SetCurrentCursorPos(2, 5);
    delay_print("?????????!!!!!!!!!!");
    SetCurrentCursorPos(2, 6);
    printf("'그럼 나는 뭐지?....애 왜 사람 헷갈리게 하지?..'");
    Sleep(500);
    SetCurrentCursorPos(2, 8);
    delay_print("그리고 먼저 만나자고 해서 고마워");
    SetCurrentCursorPos(2, 10);
    printf("(이건 플러팅인가...애 왜이러지?.. 근데 안친한데 오늘 나와준것만해도.. )");
    Sleep(500);
    SetCurrentCursorPos(2, 12);
    printf("(나도 애 괜찮다고 생각한것도 있고.. 외롭기도하고.. 친구만들겸 남친이나 만들까?..)");
    Sleep(500);
    SetCurrentCursorPos(2, 14);
    printf("(후회 할꺼같긴한데 질러보자!..)");
    Sleep(500);
    SetCurrentCursorPos(2, 16);
    printf("나도 재미있었어.. 나 할말이 있는데..");
    sound2();
    SetCurrentCursorPos(2, 18);
    delay_print("응?? 할 말??");
    Sleep(1000);
    SetCurrentCursorPos(2, 20);
    delay_print("......그게....");
    SetCurrentCursorPos(2, 22);
    printf("\033[34m1.저기 .. 나랑 사귈래??..\033[0m");
    SetCurrentCursorPos(2, 23);
    printf("\033[34m2. 너와 진지하게 만나고 싶은데 너는 어때?\033[0m");
    SetCurrentCursorPos(2, 24);
    printf("\033[34m3.넌 너무 멋있는거 같아 너랑 만나고싶어\033[0m");
    SetCurrentCursorPos(0, 26);
    printf("\033[33m번호를 입력해주세요:\033[0m");

}
    